#pragma once

#ifndef TalkyHooksH
#define TalkyHooksH

#include "CommonFuncs.h"
#include "Morrowind.h"
#include "MathTools.h"
#include "HookTools.h"

//====================================================================================
void _cdecl __OpenCloseBookAndDoc(void);
void _cdecl __OpenBook(HVL LPSTR BookText);
void _cdecl __OpenDocument(HVL MORROWIND::PCWindow TxtClass,HVL LPSTR DocText);
BOOL _cdecl __MakeJournalPage(HVL MORROWIND::PCWindow TxtClass00,HVL short TgtWndID00,HVL DWORD UnkRndTime,HVL short TgtWndID01,HVL MORROWIND::PCWindow TxtClass01);
BOOL _cdecl __ChangeBookPageForward(HVL MORROWIND::PCWindow TxtClass00,HVL short TgtWndID00,HVL DWORD UnkRndTime,HVL short TgtWndID01,HVL MORROWIND::PCWindow TxtClass01);
BOOL _cdecl __ChangeBookPageBackward(HVL MORROWIND::PCWindow TxtClass00,HVL short TgtWndID00,HVL DWORD UnkRndTime,HVL short TgtWndID01,HVL MORROWIND::PCWindow TxtClass01);

BOOL _cdecl __CamLookDisabling(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL DWORD Reg_ESI,HVL MORROWIND::PCObjMACP Player,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __CamLookVertDelta(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL DWORD Reg_ESI,HVL MORROWIND::PCObjMACP Player,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __CamLookHortDelta(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL DWORD Reg_ESI,HVL MORROWIND::PCObjMACP Player,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __PlayerSneakLocking(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL DWORD Reg_ESI,HVL MORROWIND::PCObjMACP Player,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __ActorAiActionChanging(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL MORROWIND::PCObjMACT Actor,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __MenuFreezingWaterRiffles(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL PVOID UnkClass,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL MORROWIND::PCGameScene GameClass,...);
BOOL _cdecl __MenuFreezingDoors(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL MORROWIND::PCObjREFR ObjectA,HVL MORROWIND::PCObjREFR ObjectB,HVL MORROWIND::PCObjCELL Cell,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL MORROWIND::PCGameScene GameClass,...);
BOOL _cdecl __MenuFreezingShadows(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL PVOID UnkClass,HVL DWORD Reg_ESI,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL MORROWIND::PCGameScene GameClass,...);
BOOL _cdecl __MenuFreezingCompass(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL PVOID UnkClass,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL MORROWIND::PCGameScene GameClass,...);
BOOL _cdecl __MenuFreezingActiveObjects(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL MORROWIND::PCGameScene GameClass,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL PVOID UnkClass,HVL DWORD Reg_EAX,...);
BOOL _cdecl __DlgAllowingHeadTrack(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD UnkValue,HVL PVOID UnkClass,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL MORROWIND::PCGameScene GameClass,HVL DWORD Reg_EAX,...);
BOOL _cdecl __StartDialogue(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL MORROWIND::PCObjMACT Actor,HVL MORROWIND::PCObjDIAL Dialogue,HVL DWORD Reg_ESP,HVL MORROWIND::PCObjINFO DlgInfo,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __ControlCurDlgActorAI(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL PVOID UnkClass,HVL MORROWIND::PCObjMACT Actor,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL MORROWIND::PCObjREFR ActorRef,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __ToggleGM(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL DWORD Reg_ESI,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __IsJournalAllowed(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL DWORD Reg_ESI,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD JnlKeyState,...);

BOOL _cdecl __ExitMenuMode(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL DWORD Reg_EDI,HVL DWORD Reg_ESI,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL DWORD Reg_EBX,HVL DWORD Reg_EDX,HVL DWORD Reg_ECX,HVL DWORD Reg_EAX,...);
BOOL _cdecl __MenuModeAnimationFreezing(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL MORROWIND::PCRenderer Renderer,HVL DWORD Reg_ESI,HVL DWORD Reg_EBP,HVL DWORD Reg_ESP,HVL BOOL PauseAnims2,HVL MORROWIND::PCObjREFR SomeRef,HVL MORROWIND::PCGameScene GameClass,HVL BOOL PauseAnims,...);
BOOL _cdecl __ChangeDlgTopic(HVL DWORD Reg_EIP,HVL DWORD Reg_EFL,HVL PVOID CUnkCopyA,HVL PVOID CUnkCopyB,HVL MORROWIND::PCObjDIAL Dialogue,HVL DWORD Reg_ESP,HVL MORROWIND::PCObjINFO Info,HVL DWORD Reg_EDX,HVL PVOID CUnkCopyC,HVL DWORD Reg_EAX,HVL long Und0,HVL long Und1,HVL PVOID RetAddr,HVL PVOID Unkn00, HVL LPSTR Text, HVL DWORD Type, HVL DWORD Unkn01,HVL MORROWIND::PCObjMACT Actor,...);

//====================================================================================
#endif
